import { TempReceiptPayload } from "./schema";

export const mockTempReceiptPayload: TempReceiptPayload = {
  last_confirmation: false,
  last_receipt: {
    users: ["Alice", "Bob", "Charlie"],
    receipt: {
      items: [
        {
          name: "Hong Kong Milk Tea (Cold)",
          quantity: 4,
          subtotal: 14.0,
          indiv: [],
          shared: [],
        },
        {
          name: "Honey Sea Coconut with Longan",
          quantity: 1,
          subtotal: 3.5,
          indiv: [],
          shared: [],
        },
        {
          name: "BBQ Pork Rice",
          quantity: 1,
          subtotal: 3.5,
          indiv: [],
          shared: [],
        },
        {
          name: "Char Siew Bao",
          quantity: 1,
          subtotal: 2.9,
          indiv: [],
          shared: [],
        },
        {
          name: "Red Bean Paste Bao",
          quantity: 1,
          subtotal: 2.1,
          indiv: [],
          shared: [],
        },
        {
          name: "Mango with Pomelo & Sago",
          quantity: 1,
          subtotal: 4.8,
          indiv: [],
          shared: [],
        },
        {
          name: "Hong Kong Style Milk Tea",
          quantity: 1,
          subtotal: 6.8,
          indiv: [],
          shared: [],
        },
        {
          name: "Red Bean Paste Pancake",
          quantity: 1,
          subtotal: 4.8,
          indiv: [],
          shared: [],
        },
        {
          name: "Grass Jelly Drink",
          quantity: 1,
          subtotal: 2.7,
          indiv: [],
          shared: [],
        },
        {
          name: "Yam Paste w/ Ginkgo Nut",
          quantity: 1,
          subtotal: 4.5,
          indiv: [],
          shared: [],
        },
        {
          name: "Sweet Potato Salted Egg Custard Ball",
          quantity: 1,
          subtotal: 3.8,
          indiv: [],
          shared: [],
        },
        {
          name: "Siew Mai",
          quantity: 3,
          subtotal: 8.7,
          indiv: [],
          shared: [],
        },
        {
          name: "Har Gow",
          quantity: 3,
          subtotal: 12.6,
          indiv: [],
          shared: [],
        },
        {
          name: "Rice Roll with Prawn",
          quantity: 1,
          subtotal: 5.0,
          indiv: [],
          shared: [],
        },
        {
          name: "Bean Curd Prawn Roll",
          quantity: 3,
          subtotal: 12.6,
          indiv: [],
          shared: [],
        },
        {
          name: "Fried Prawn Dumpling",
          quantity: 1,
          subtotal: 5.4,
          indiv: [],
          shared: [],
        },
        {
          name: "Water Chestnut Drink",
          quantity: 1,
          subtotal: 2.7,
          indiv: [],
          shared: [],
        },
        {
          name: "Xiao Long Bao",
          quantity: 1,
          subtotal: 5.9,
          indiv: [],
          shared: [],
        },
        {
          name: "Spring Roll",
          quantity: 1,
          subtotal: 2.8,
          indiv: [],
          shared: [],
        },
        {
          name: "Salted Egg Yolk Custard Bao (Fried)",
          quantity: 1,
          subtotal: 6.0,
          indiv: [],
          shared: [],
        },
        {
          name: "Glutinous Rice with Chicken",
          quantity: 1,
          subtotal: 3.5,
          indiv: [],
          shared: [],
        },
        {
          name: "Portuguese Egg Tart",
          quantity: 1,
          subtotal: 4.4,
          indiv: [],
          shared: [],
        },
        {
          name: "Prawn Hor Fun in Creamy Egg Sauce",
          quantity: 1,
          subtotal: 8.8,
          indiv: [],
          shared: [],
        },
        {
          name: "Barley Drink",
          quantity: 1,
          subtotal: 2.7,
          indiv: [],
          shared: [],
        },
      ],
      subtotal: 134.5,
      service_charge: 13.45,
      gst: 13.32,
      total: 161.27,
      currency: "SGD",
    },
  },
};
