class ManageBillStates:
    EXPENSE_NAME = 1
    EXPENSE_RECEIPT_UPLOAD = 2
    EXPENSE_RECEIPT_CONFIRM = 3
    EXPENSE_AMOUNT = 4
    EXPENSE_PAID_BY = 5
    EXPENSE_SPLIT_TYPE = 6
    EXPENSE_PARTICIPANTS = 7
    EXPENSE_CUSTOM_SPLIT = 8
    EXPENSE_CONFIRM = 9
    EXPENSE_CUSTOM_AMOUNT = 10
    EXPENSE_MULTIPLIER = 11
    VIEW_EXPENSE = 12
    EDIT_OR_GO_BACK = 13
    DELETE_EXPENSE = 14
